services:
  asp_demo_db:
    container_name: asp_demo_db
    build:
      context: ./SQLServer
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:1433"
    networks:
      - db-network
    environment:
      ACCEPT_EULA: ${BACKEND_ACCEPT_EULA}
      MSSQL_SA_PASSWORD: ${BACKEND_PASSWORD}
  asp_demo_frontend:
    container_name: asp_demo_frontend
    build:
      context: ./React
      dockerfile: Dockerfile
      args:
        - FRONTEND_TEMPLATE_REPO=${FRONTEND_TEMPLATE_REPO}
    volumes:
      - frontend-volume:/usr/src/app/dist
    command: npm run dev
  asp_demo_api:
    container_name: asp_demo_api
    build:
      context: ./ASPNET
      dockerfile: Dockerfile
      args:
        - API_TEMPLATE_REPO=${API_TEMPLATE_REPO}
    ports:
      - "${API_PORT}:5000"
    networks:
      - db-network
      - api-network
    command: dotnet watch
  asp_demo_proxy:
    container_name: asp_demo_proxy
    build:
      context: ./NGinx
      dockerfile: Dockerfile
    ports:
      - "${PROXY_PORT}:80"
      - "${PROXY_PORT_SSL}:443"
    volumes:
      - frontend-volume:/etc/nginx/frontend
    networks:
      - api-network

networks:
  db-network:
  api-network:

volumes:
  frontend-volume: